import { Film, Venue } from "@/lib/domain";
import { slugify } from "@/lib/utils";

function makeVenueTag(name: string): string {
  return name;
}

export const curatedVenues: Venue[] = [
  {
    id: "venue-film-forum",
    name: "Film Forum",
    slug: "film-forum",
    website: "https://filmforum.org",
    address: "209 W Houston St, New York, NY",
    borough: "Manhattan",
    lat: 40.7285,
    lng: -74.0058,
    neighborhood: "SoHo",
    nearestSubwayStops: ["Houston St", "West 4th St"],
    active: true,
    adapterType: "event_page",
    tags: [makeVenueTag("Film Forum")]
  },
  {
    id: "venue-ifc-center",
    name: "IFC Center",
    slug: "ifc-center",
    website: "https://www.ifccenter.com",
    address: "323 6th Ave, New York, NY",
    borough: "Manhattan",
    lat: 40.7303,
    lng: -74.0018,
    neighborhood: "Greenwich Village",
    nearestSubwayStops: ["West 4th St", "14 St"],
    active: true,
    adapterType: "structured_html",
    notes: "Tier 1 seed venue",
    tags: [makeVenueTag("IFC Center")]
  },
  {
    id: "venue-quad-cinema",
    name: "Quad Cinema",
    slug: "quad-cinema",
    website: "https://quadcinema.com",
    address: "34 W 13th St, New York, NY",
    borough: "Manhattan",
    lat: 40.7361,
    lng: -73.9954,
    neighborhood: "Greenwich Village",
    nearestSubwayStops: ["14 St", "Union Square"],
    active: true,
    adapterType: "event_page",
    tags: [makeVenueTag("Quad Cinema")]
  },
  {
    id: "venue-angelika-film-center",
    name: "Angelika Film Center",
    slug: "angelika-film-center",
    website: "https://www.angelikafilmcenter.com/nyc",
    address: "18 W Houston St, New York, NY",
    borough: "Manhattan",
    lat: 40.7278,
    lng: -73.9997,
    neighborhood: "NoHo",
    nearestSubwayStops: ["Broadway-Lafayette St", "Bleecker St"],
    active: true,
    adapterType: "event_page",
    includeRules: ["specialty-only"],
    tags: [makeVenueTag("Angelika Film Center")]
  },
  {
    id: "venue-village-east",
    name: "Village East by Angelika",
    slug: "village-east-by-angelika",
    website: "https://www.angelikafilmcenter.com/villageeast/signature-programming",
    address: "181-189 2nd Ave, New York, NY",
    borough: "Manhattan",
    lat: 40.7309,
    lng: -73.9865,
    neighborhood: "East Village",
    nearestSubwayStops: ["Astor Place", "14 St-Union Square"],
    active: true,
    adapterType: "event_page",
    includeRules: ["signature-programming-only"],
    tags: [makeVenueTag("Village East by Angelika")]
  },
  {
    id: "venue-metrograph",
    name: "Metrograph",
    slug: "metrograph",
    website: "https://metrograph.com",
    address: "7 Ludlow St, New York, NY",
    borough: "Manhattan",
    lat: 40.7188,
    lng: -73.9881,
    neighborhood: "Lower East Side",
    nearestSubwayStops: ["Delancey St-Essex St"],
    active: true,
    adapterType: "event_page",
    tags: [makeVenueTag("Metrograph")]
  },
  {
    id: "venue-anthology",
    name: "Anthology Film Archives",
    slug: "anthology-film-archives",
    website: "https://anthologyfilmarchives.org",
    address: "32 2nd Ave, New York, NY",
    borough: "Manhattan",
    lat: 40.7249,
    lng: -73.9905,
    neighborhood: "East Village",
    nearestSubwayStops: ["2 Av", "Bleecker St"],
    active: true,
    adapterType: "event_page",
    tags: [makeVenueTag("Anthology Film Archives")]
  },
  {
    id: "venue-cinema-village",
    name: "Cinema Village",
    slug: "cinema-village",
    website: "https://cinemavillage.com",
    address: "22 E 12th St, New York, NY",
    borough: "Manhattan",
    lat: 40.7333,
    lng: -73.9936,
    neighborhood: "Greenwich Village",
    nearestSubwayStops: ["Union Square"],
    active: true,
    adapterType: "event_page",
    tags: [makeVenueTag("Cinema Village")]
  },
  {
    id: "venue-film-noir",
    name: "Film Noir Cinema",
    slug: "film-noir-cinema",
    website: "https://www.filmnoircinema.com",
    address: "122 Meserole Ave, Brooklyn, NY",
    borough: "Brooklyn",
    lat: 40.7274,
    lng: -73.9533,
    neighborhood: "Greenpoint",
    nearestSubwayStops: ["Greenpoint Ave"],
    active: true,
    adapterType: "ics",
    notes: "Tier 1 seed venue",
    tags: [makeVenueTag("Film Noir Cinema")]
  },
  {
    id: "venue-roxy",
    name: "Roxy Cinema New York",
    slug: "roxy-cinema-new-york",
    website: "https://www.roxycinemanewyork.com",
    address: "2 6th Ave, New York, NY",
    borough: "Manhattan",
    lat: 40.7194,
    lng: -74.0055,
    neighborhood: "Tribeca",
    nearestSubwayStops: ["Canal St", "Franklin St"],
    active: true,
    adapterType: "event_page",
    tags: [makeVenueTag("Roxy Cinema New York")]
  },
  {
    id: "venue-flc",
    name: "Film at Lincoln Center",
    slug: "film-at-lincoln-center",
    website: "https://www.filmlinc.org",
    address: "144 W 65th St, New York, NY",
    borough: "Manhattan",
    lat: 40.7725,
    lng: -73.9835,
    neighborhood: "Lincoln Square",
    nearestSubwayStops: ["66 St-Lincoln Center"],
    active: true,
    adapterType: "event_page",
    tags: [makeVenueTag("Film at Lincoln Center")]
  },
  {
    id: "venue-paris-theater",
    name: "Paris Theater",
    slug: "paris-theater",
    website: "https://paristheaternyc.com",
    address: "4 W 58th St, New York, NY",
    borough: "Manhattan",
    lat: 40.7645,
    lng: -73.9769,
    neighborhood: "Midtown",
    nearestSubwayStops: ["57 St", "5 Av/59 St"],
    active: true,
    adapterType: "event_page",
    tags: [makeVenueTag("Paris Theater")]
  },
  {
    id: "venue-firehouse",
    name: "Firehouse: DCTV’s Cinema for Documentary Film",
    slug: "firehouse-dctvs-cinema-for-documentary-film",
    website: "https://dctvny.org/s/firehousecinema",
    address: "87 Lafayette St, New York, NY",
    borough: "Manhattan",
    lat: 40.7168,
    lng: -74.0014,
    neighborhood: "Chinatown",
    nearestSubwayStops: ["Canal St"],
    active: true,
    adapterType: "event_page",
    tags: [makeVenueTag("Firehouse: DCTV’s Cinema for Documentary Film")]
  },
  {
    id: "venue-bam",
    name: "BAM Rose Cinemas",
    slug: "bam-rose-cinemas",
    website: "https://www.bam.org/film",
    address: "30 Lafayette Ave, Brooklyn, NY",
    borough: "Brooklyn",
    lat: 40.6861,
    lng: -73.9772,
    neighborhood: "Fort Greene",
    nearestSubwayStops: ["DeKalb Ave", "Atlantic Av-Barclays Ctr"],
    active: true,
    adapterType: "event_page",
    tags: [makeVenueTag("BAM Rose Cinemas")]
  },
  {
    id: "venue-nitehawk-williamsburg",
    name: "Nitehawk Cinema Williamsburg",
    slug: "nitehawk-cinema-williamsburg",
    website: "https://nitehawkcinema.com/williamsburg",
    address: "136 Metropolitan Ave, Brooklyn, NY",
    borough: "Brooklyn",
    lat: 40.7167,
    lng: -73.9625,
    neighborhood: "Williamsburg",
    nearestSubwayStops: ["Bedford Ave"],
    active: true,
    adapterType: "event_page",
    tags: [makeVenueTag("Nitehawk Cinema Williamsburg")]
  },
  {
    id: "venue-nitehawk-prospect-park",
    name: "Nitehawk Cinema Prospect Park",
    slug: "nitehawk-cinema-prospect-park",
    website: "https://nitehawkcinema.com/prospectpark",
    address: "188 Prospect Park West, Brooklyn, NY",
    borough: "Brooklyn",
    lat: 40.6604,
    lng: -73.9792,
    neighborhood: "Park Slope",
    nearestSubwayStops: ["15 St-Prospect Park"],
    active: true,
    adapterType: "event_page",
    tags: [makeVenueTag("Nitehawk Cinema Prospect Park")]
  },
  {
    id: "venue-spectacle",
    name: "Spectacle Theater",
    slug: "spectacle-theater",
    website: "https://www.spectacletheater.com",
    address: "124 S 3rd St, Brooklyn, NY",
    borough: "Brooklyn",
    lat: 40.7113,
    lng: -73.9631,
    neighborhood: "Williamsburg",
    nearestSubwayStops: ["Marcy Ave", "Bedford Ave"],
    active: true,
    adapterType: "event_page",
    notes: "Tier 1 seed venue",
    tags: [makeVenueTag("Spectacle Theater")]
  },
  {
    id: "venue-light-industry",
    name: "Light Industry",
    slug: "light-industry",
    website: "https://www.lightindustry.org",
    address: "155 Freeman St, Brooklyn, NY",
    borough: "Brooklyn",
    lat: 40.7323,
    lng: -73.9584,
    neighborhood: "Greenpoint",
    nearestSubwayStops: ["Greenpoint Ave"],
    active: true,
    adapterType: "event_page",
    tags: [makeVenueTag("Light Industry")]
  },
  {
    id: "venue-e-flux",
    name: "e-flux Screening Room",
    slug: "e-flux-screening-room",
    website: "https://www.e-flux.com/film/screening-room",
    address: "172 Classon Ave, Brooklyn, NY",
    borough: "Brooklyn",
    lat: 40.6875,
    lng: -73.9595,
    neighborhood: "Clinton Hill",
    nearestSubwayStops: ["Classon Ave"],
    active: true,
    adapterType: "event_page",
    tags: [makeVenueTag("e-flux Screening Room")]
  },
  {
    id: "venue-millennium",
    name: "Millennium Film Workshop",
    slug: "millennium-film-workshop",
    website: "https://millenniumfilm.org",
    address: "167 Wilson Ave, Brooklyn, NY",
    borough: "Brooklyn",
    lat: 40.7051,
    lng: -73.925,
    neighborhood: "Bushwick",
    nearestSubwayStops: ["Jefferson St"],
    active: true,
    adapterType: "event_page",
    tags: [makeVenueTag("Millennium Film Workshop")]
  },
  {
    id: "venue-syndicated",
    name: "Syndicated",
    slug: "syndicated",
    website: "https://syndicatedbk.com",
    address: "40 Bogart St, Brooklyn, NY",
    borough: "Brooklyn",
    lat: 40.7051,
    lng: -73.9331,
    neighborhood: "Bushwick",
    nearestSubwayStops: ["Morgan Ave"],
    active: true,
    adapterType: "event_page",
    tags: [makeVenueTag("Syndicated")]
  },
  {
    id: "venue-maysles",
    name: "Maysles Documentary Center",
    slug: "maysles-documentary-center",
    website: "https://www.maysles.org",
    address: "343 Malcolm X Blvd, New York, NY",
    borough: "Manhattan",
    lat: 40.8106,
    lng: -73.9447,
    neighborhood: "Harlem",
    nearestSubwayStops: ["125 St"],
    active: true,
    adapterType: "event_page",
    tags: [makeVenueTag("Maysles Documentary Center")]
  },
  {
    id: "venue-moving-image",
    name: "Museum of the Moving Image",
    slug: "museum-of-the-moving-image",
    website: "https://movingimage.org/whats-on/screenings-and-series",
    address: "36-01 35th Ave, Astoria, NY",
    borough: "Queens",
    lat: 40.7563,
    lng: -73.9235,
    neighborhood: "Astoria",
    nearestSubwayStops: ["36 Ave", "Steinway St"],
    active: true,
    adapterType: "event_page",
    includeRules: ["ticketed-only"],
    notes: "Tier 1 seed venue",
    tags: [makeVenueTag("Museum of the Moving Image")]
  },
  {
    id: "venue-low-cinema",
    name: "Low Cinema",
    slug: "low-cinema",
    website: "https://lowcinema.com",
    address: "188 Loisaida Ave, New York, NY",
    borough: "Manhattan",
    lat: 40.7222,
    lng: -73.9794,
    neighborhood: "Lower East Side",
    nearestSubwayStops: ["1 Av", "Delancey St-Essex St"],
    active: true,
    adapterType: "structured_html",
    notes: "Tier 1 seed venue",
    tags: [makeVenueTag("Low Cinema")]
  },
  {
    id: "venue-moma",
    name: "MoMA Film Screenings",
    slug: "moma-film-screenings",
    website: "https://www.moma.org/calendar/film",
    address: "11 W 53rd St, New York, NY",
    borough: "Manhattan",
    lat: 40.7614,
    lng: -73.9776,
    neighborhood: "Midtown",
    nearestSubwayStops: ["5 Av/53 St"],
    active: true,
    adapterType: "event_page",
    includeRules: ["public-booking-only"],
    tags: [makeVenueTag("MoMA Film Screenings")]
  },
  {
    id: "venue-amc-lincoln-square",
    name: "AMC Lincoln Square 13",
    slug: "amc-lincoln-square-13",
    website: "https://www.amctheatres.com/movie-theatres/new-york-city/amc-lincoln-square-13",
    address: "1998 Broadway, New York, NY",
    borough: "Manhattan",
    lat: 40.774,
    lng: -73.9824,
    neighborhood: "Lincoln Square",
    nearestSubwayStops: ["66 St-Lincoln Center"],
    active: true,
    adapterType: "structured_html",
    includeRules: ["imax-only", "special-events-only"],
    tags: [makeVenueTag("AMC Lincoln Square 13")]
  },
  {
    id: "venue-alamo-drafthouse",
    name: "Alamo Drafthouse",
    slug: "alamo-drafthouse",
    website: "https://drafthouse.com/nyc",
    address: "445 Albee Square W, Brooklyn, NY",
    borough: "Brooklyn",
    lat: 40.6909,
    lng: -73.9832,
    neighborhood: "Downtown Brooklyn",
    nearestSubwayStops: ["DeKalb Ave", "Jay St-MetroTech"],
    active: true,
    adapterType: "event_page",
    includeRules: ["specialty-only", "repertory-only"],
    tags: [makeVenueTag("Alamo Drafthouse")]
  }
];

export const filmCatalog: Film[] = [
  {
    id: "film-house-1977",
    slug: "house-1977",
    canonicalTitle: "House",
    originalTitle: "Hausu",
    releaseYear: 1977,
    runtimeMinutes: 88,
    directors: ["Nobuhiko Obayashi"],
    countries: ["Japan"],
    languages: ["Japanese"],
    metadataSourceIds: { tmdb: "25623" },
    synopsis:
      "A schoolgirl and six classmates visit an ailing aunt's country estate and are swallowed into a delirious haunted-house fantasia.",
    criterionLikely: true
  },
  {
    id: "film-the-housemaid-1960",
    slug: "the-housemaid-1960",
    canonicalTitle: "The Housemaid",
    releaseYear: 1960,
    runtimeMinutes: 111,
    directors: ["Kim Ki-young"],
    countries: ["South Korea"],
    languages: ["Korean"],
    metadataSourceIds: { tmdb: "53031" },
    synopsis:
      "A piano teacher's family is destroyed when a volatile domestic worker turns desire and class anxiety into outright catastrophe.",
    criterionLikely: true
  },
  {
    id: "film-paris-texas",
    slug: "paris-texas",
    canonicalTitle: "Paris, Texas",
    releaseYear: 1984,
    runtimeMinutes: 145,
    directors: ["Wim Wenders"],
    countries: ["West Germany", "France", "United Kingdom"],
    languages: ["English"],
    metadataSourceIds: { tmdb: "655" },
    synopsis:
      "A drifter re-emerges from the desert and slowly tries to reconnect with the son and wife he abandoned years earlier.",
    criterionLikely: true
  },
  {
    id: "film-world-on-a-wire",
    slug: "world-on-a-wire",
    canonicalTitle: "World on a Wire",
    releaseYear: 1973,
    runtimeMinutes: 212,
    directors: ["Rainer Werner Fassbinder"],
    countries: ["West Germany"],
    languages: ["German"],
    metadataSourceIds: { tmdb: "42053" },
    synopsis:
      "A cybernetic engineer suspects his reality is itself a simulation after a project director vanishes without explanation.",
    criterionLikely: true
  },
  {
    id: "film-killer-of-sheep",
    slug: "killer-of-sheep",
    canonicalTitle: "Killer of Sheep",
    releaseYear: 1978,
    runtimeMinutes: 81,
    directors: ["Charles Burnett"],
    countries: ["United States"],
    languages: ["English"],
    metadataSourceIds: { tmdb: "93826" },
    synopsis:
      "Charles Burnett's landmark portrait follows a slaughterhouse worker and his family through the textures of Watts life.",
    criterionLikely: true
  },
  {
    id: "film-born-in-flames",
    slug: "born-in-flames",
    canonicalTitle: "Born in Flames",
    releaseYear: 1983,
    runtimeMinutes: 90,
    directors: ["Lizzie Borden"],
    countries: ["United States"],
    languages: ["English"],
    metadataSourceIds: { tmdb: "41383" },
    synopsis:
      "Ten years after a democratic socialist revolution, feminist groups in New York radicalize against the new status quo.",
    criterionLikely: true
  },
  {
    id: "film-2001-a-space-odyssey",
    slug: "2001-a-space-odyssey",
    canonicalTitle: "2001: A Space Odyssey",
    releaseYear: 1968,
    runtimeMinutes: 149,
    directors: ["Stanley Kubrick"],
    countries: ["United Kingdom", "United States"],
    languages: ["English"],
    metadataSourceIds: { tmdb: "62" },
    synopsis:
      "Kubrick's cosmic epic links prehistoric violence, machine consciousness, and metaphysical rebirth through monumentally scaled images.",
    criterionLikely: false
  },
  {
    id: "film-enter-the-dragon",
    slug: "enter-the-dragon",
    canonicalTitle: "Enter the Dragon",
    releaseYear: 1973,
    runtimeMinutes: 102,
    directors: ["Robert Clouse"],
    countries: ["Hong Kong", "United States"],
    languages: ["English", "Cantonese"],
    metadataSourceIds: { tmdb: "9461" },
    synopsis:
      "Bruce Lee infiltrates a private martial-arts tournament that doubles as a criminal operation on a remote island.",
    criterionLikely: false
  },
  {
    id: "film-possession",
    slug: "possession",
    canonicalTitle: "Possession",
    releaseYear: 1981,
    runtimeMinutes: 124,
    directors: ["Andrzej Zulawski"],
    countries: ["France", "West Germany"],
    languages: ["English", "French"],
    metadataSourceIds: { tmdb: "21484" },
    synopsis:
      "A collapsing Berlin marriage spirals into bodily horror, espionage paranoia, and emotional extremity.",
    criterionLikely: true
  },
  {
    id: "film-the-color-of-pomegranates",
    slug: "the-color-of-pomegranates",
    canonicalTitle: "The Color of Pomegranates",
    releaseYear: 1969,
    runtimeMinutes: 79,
    directors: ["Sergei Parajanov"],
    countries: ["Soviet Union"],
    languages: ["Armenian"],
    metadataSourceIds: { tmdb: "42236" },
    synopsis:
      "A visionary collage transforms the life of poet Sayat-Nova into a sequence of iconographic tableaux.",
    criterionLikely: true
  },
  {
    id: "film-eephus",
    slug: "eephus",
    canonicalTitle: "Eephus",
    releaseYear: 2025,
    runtimeMinutes: 98,
    directors: ["Carson Lund"],
    countries: ["United States"],
    languages: ["English"],
    metadataSourceIds: { tmdb: "1249778" },
    synopsis:
      "A low-stakes adult baseball game stretches into an elegy for vanishing leisure, male friendship, and community ritual.",
    criterionLikely: false
  },
  {
    id: "film-funeral-parade-of-roses",
    slug: "funeral-parade-of-roses",
    canonicalTitle: "Funeral Parade of Roses",
    releaseYear: 1969,
    runtimeMinutes: 105,
    directors: ["Toshio Matsumoto"],
    countries: ["Japan"],
    languages: ["Japanese"],
    metadataSourceIds: { tmdb: "64832" },
    synopsis:
      "An avant-garde, queer, and self-reflexive odyssey through late-1960s Tokyo nightlife refracts Oedipus into underground cinema.",
    criterionLikely: true
  },
  {
    id: "film-in-the-mood-for-love",
    slug: "in-the-mood-for-love",
    canonicalTitle: "In the Mood for Love",
    releaseYear: 2000,
    runtimeMinutes: 98,
    directors: ["Wong Kar-wai"],
    countries: ["Hong Kong", "France"],
    languages: ["Cantonese", "Shanghainese"],
    metadataSourceIds: { tmdb: "843" },
    synopsis:
      "Two neighbors in 1960s Hong Kong discover their spouses are having an affair and drift into an exquisitely restrained intimacy.",
    criterionLikely: true
  }
];

export const filmByNormalizedTitle = new Map(
  filmCatalog.map((film) => [slugify(`${film.canonicalTitle}-${film.releaseYear ?? "unknown"}`), film])
);
